### ISSUE TITLE
Proper citation(s)

### ISSUE THREAD

**Issue by vvp-nsk** [BoothGroup/ebcc#62]
Hej!

Could you please specify on how to cite the EBCC package, especially regarding implementations of the DCSD and BDCD methods?

Thank you in advance!

With best regards, 
Victor

**Comment by obackhouse** [comment]
Hi, nice to hear you have something worth citing. Since we haven't (yet) got around to publishing a paper on `ebcc`, I've linked Zenodo and triggered a new release, so there is now a DOI for the package: https://zenodo.org/doi/10.5281/zenodo.13141785. There are citation details at the bottom of that page.

For DCSD I would cite the following paper which I used when generating the code: https://doi.org/10.1063/1.4944087. For BDCD, perhaps the original Brueckner coupled cluster paper, or if there is one specific for BDCD then use that, but I didn't use any particular paper.

**Comment by vvp-nsk** [comment]
Hej!

Thanks for your prompt reply. I will follow your guidelines. 

Even being written in _all-in-RAM_ paradigm, the EBCC package is useful, but it needs a kind of promotion.  At the very least, EBCC should be mentioned within the PySCF's interfaces listed at: 
https://pyscf.org/user/extensions.html

In my eye, the newly developed CC codes such as EBCC and [CCPY](https://github.com/piecuch-group/ccpy) must take their rightful place in computational chemistry.

Thank you for your work and support!

With best regards, 
Victor
